Feature/sound effects2
cap4053-cheeky-pixels/EmbodyGame pull request #160
Opened 2019-04-05 00:54 UTC by klein1992

2019-04-05 01:22 UTC, CameroonDoge commented
I like the snake sound effect, the laser sound effect, and the sound effect when the cubex enemies die. I'm not so sure about the player damage sound effect or the one for the kat enemy.

2019-04-05 12:54 UTC, AleksandrHovhannisyan commented on Assets/Scripts/Weapons/Weapon.cs
> +    public AudioSource fireAudio;
I would add this to ProjectileWeapon.cs instead of Weapon.cs. Or maybe just call it `attackAudio`. At this point, though, it doesn't really matter.

2019-04-05 13:07 UTC, AleksandrHovhannisyan requested changes
Audio I like:

- Laser weapon
- Triple-shot weapon
- Tenticle death sound

Audio I don't like:

- Cubex death sound (too loud, and also kinda doesn't fit them)
- Player damage SFX (too human—though tbh, I don't think we need one for the player getting hit)
- Kat damage SFX (sounds like someone's shouting "bro")
- Cruz damage SFX (doesn't make sense; maybe add some wood snapping instead?)
- Basic weapon SFX (doesn't fit the aesthetic well)

2019-04-07 00:46 UTC, klein1992 commented
I've changed the cubex death sound, basic weapon and player damage sound. Please let me know if any are satisfactory

2019-04-07 13:51 UTC, AleksandrHovhannisyan commented
Cameran and I left you feedback on sounds we don't like (e.g., the Kat enemy's and Cruz's). Please take this into consideration.

2019-04-09 12:53 UTC, klein1992 commented
I have updated the sound for cubexenemy which I really like, the damage sound for the player which I like as well (sounds less human), the sound for cruz death (kinda hard to find a good sound for cruz), and the sound for Kat enemy death. I also made it so that only if the player is shooting, fire audio will play.

2019-04-09 19:20 UTC, AleksandrHovhannisyan commented
The cubex sound you had before this one was better...

2019-04-09 20:15 UTC, Jazy5552 commented
rip the enemy prefabs :'(

2019-04-09 20:32 UTC, Jazy5552 commented
Not gonna lie, these sounds are pretty bad XD The cruz farting when it dies killed me! The basic weapon fire sound is definitely bad, sounds like a hamster sneezing.

The only good sounds are the triple shot sound (Maybe just use this for all weapons and keep nice and soft so it doesn't get annoying), and the possession sound.

Not a fan of anything else. I might try my hand at some sounds and maybe organize a doc to track them.

2019-04-12 01:05 UTC, closed without merging